# Generated by Django 2.2.16 on 2020-09-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=64)),
                ('text', models.TextField(blank=True)),
                ('file', models.ImageField(blank=True, upload_to='file')),
                ('url', models.URLField(blank=True, max_length=1024)),
                ('root', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('children', models.ManyToManyField(blank=True, related_name='_entry_children_+', to='core.Entry')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
