# Generated by Django 2.2.16 on 2020-09-22 23:05

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
