# Generated by Django 2.2.16 on 2020-09-22 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200922_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='url',
        ),
    ]
