# Generated by Django 2.2.16 on 2020-09-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_entry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='children',
        ),
        migrations.AddField(
            model_name='entry',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='_entry_parent_+', to='core.Entry'),
        ),
    ]
