# Generated by Django 2.2.16 on 2020-09-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200923_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='parent',
        ),
        migrations.AddField(
            model_name='entry',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='_entry_parents_+', to='core.Entry'),
        ),
    ]
