# Generated by Django 2.2.16 on 2020-09-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200923_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='name_parent',
            field=models.BooleanField(default=False, help_text="Include parent's name (if only one parent) as prefix."),
        ),
    ]
