# Generated by Django 2.2.16 on 2020-09-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_entry_name_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='name_parent',
            field=models.BooleanField(default=False, help_text="Use parent's name as prefix (if only one parent)."),
        ),
    ]
