# Generated by Django 2.2.16 on 2020-09-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200923_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='core.Entry'),
        ),
    ]
