# Generated by Django 2.2.16 on 2020-09-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200923_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='name_parent',
        ),
    ]
