# Generated by Django 2.2.16 on 2020-09-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_entry_name_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='name_parent',
            field=models.ForeignKey(blank=True, help_text="Use this parent's name as prefix.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Entry'),
        ),
    ]
